"""change field name RealTime

Revision ID: e2144f13f34c
Revises: 
Create Date: 2024-06-24 14:11:45.764222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2144f13f34c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('realtime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('soil_pot', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('soil_temp', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('soil_ph', sa.Float(), nullable=False))
        batch_op.drop_column('soil_pot1')
        batch_op.drop_column('soil_temp1')
        batch_op.drop_column('soil_ph1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('realtime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('soil_ph1', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('soil_temp1', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('soil_pot1', sa.FLOAT(), nullable=False))
        batch_op.drop_column('soil_ph')
        batch_op.drop_column('soil_temp')
        batch_op.drop_column('soil_pot')

    # ### end Alembic commands ###
